#!/bin/sh

IMAGE_PART_TARGETS="/dev/mmcblk1p2 /dev/sda2"
IMAGE_PART_MOUNT="/mnt"

IMAGE_FILE="flash.img"
IMAGE_TARGET="/dev/mmcblk0"

IMAGE_PART_MOUNT_INI="$IMAGE_PART_MOUNT/flash.ini"

IMAGE_FORMAT_AUTO="auto"
IMAGE_FORMAT="$IMAGE_FORMAT_AUTO"
IMAGE_FORMAT_CMD=""

IMAGE_FLASH_STATUS_PERIOD=15

IMAGE_EXPAND=0
#IMAGE_EXPAND_PART=

